#!/bin/sh

sysroot=$1

log() {
    cmd echo "jcx.entrypoint > $1"
}

cmd() {
    "$@" > /dev/console
}

log "Welcome to the alpine initramfs!"
log "Using sysroot: $sysroot"

#log "Updating apk repositories..." 
#echo -e "/media/mmcblk0p1/apks\nhttps://alpine-cf-cdn.jcx.ovh/alpine/v3.11/main\nhttps://alpine-cf-cdn.jcx.ovh/alpine/v3.11/community"  > "$sysroot"/etc/apk/repositories

log "Copying files..."
	
# Create /jcx/services/boot folder
mkdir -p "$sysroot"/jcx/services/boot

cp /jcx/sha "$sysroot"/jcx/.sha
	
cp /jcx/runner.sh "$sysroot"/jcx/services/boot/runner
cp /jcx/setup-alpine.sh "$sysroot"/jcx/services/boot/setup-runner
cp /jcx/openrc "$sysroot"/jcx/services/boot/openrc
	
ln -s /jcx/services/boot/openrc "$sysroot"/etc/init.d/jcx-boot
ln -s /jcx/services/boot/openrc "$sysroot"/etc/runlevels/default/jcx-boot


log "Debug info:"
cmd ls -LR "$sysroot"/jcx

log "Done! Continuing with alpine boot..."
exit 0
