#!/bin/sh

sysroot=$1


quiet=false

# See if the kernel has the quiet option (/devnull for no output!)
cat "$sysroot"/proc/cmdline | grep quiet > /dev/null
if [ $? -eq 0 ]
then
    # echo "Quiet!"
    quiet=true
else
    echo "quiet not set in cmdline.txt!"
fi

debug() {
    log "(debug): $1"
}

log() {
    cmd echo "jcx.entrypoint > $1"
}

cmd() {
    if [ "$quiet" = true ]
    then
        "$@" > /dev/null
    else
        "$@" > /dev/console
    fi
}

log "Welcome to the alpine initramfs!"
log "Using sysroot: $sysroot"

# (disabled - we like being able to change these!)
# log "Adding web-based apk repositories..." 
# echo -e "$(cat "$sysroot"/etc/apk/repositories)\nhttps://alpine-cf-cdn.jcx.ovh/alpine/v3.11/main\nhttps://alpine-cf-cdn.jcx.ovh/alpine/v3.11/community"  > "$sysroot"/etc/apk/repositories

log "Copying files (initramfs --> sysroot [userland])..."

log "copy > Creating /jcx folder..."
mkdir -p "$sysroot"/jcx

debug "Copying build SHA..."
cp /jcx/sha "$sysroot"/jcx/.sha

debug "Copying sysroot data..."
cp -r /jcx/sysroot/* "$sysroot"/jcx/
	
debug "Setting up custom boot service..."
ln -s /jcx/services/boot/openrc "$sysroot"/etc/init.d/jcx-boot
ln -s /jcx/services/boot/openrc "$sysroot"/etc/runlevels/default/jcx-boot


# (unused)
# debug "Enabling parallel startup in OpenRC..."
# sed -e 's/#rc_parallel="NO"/rc_parallel="YES"/g' -i "$sysroot"/etc/rc.conf

log "Debug info:"
cmd ls -LR "$sysroot"/jcx

log "Done! Continuing with alpine boot..."
exit 0
