#!/bin/sh

# einfo a-la openrc
# https://github.com/alpinelinux/alpine-chroot-install/blob/master/alpine-chroot-install
einfo() {
	printf '\n\033[1;36m > %s\033[0m\n' "$@" >&2  # bold cyan
}

ewarn() {
	printf '\033[1;33m > %s\033[0m\n' "$@" >&2  # bold yellow
}
