#!/bin/sh

# Wrapper for openrc-run eXXX that prefixes "jcx-boot: "
sbegin () {
	ebegin "jcx-boot: $@"
}

swarn () {
	ewarn "jcx-boot: $@"
}

echoinfo() {
	read line
	einfo "jcx-boot: $line"
}

swarn "Welcome to the JCX Boot Service!"

# Set debug env based on kernel opts
JCX_VERBOSE="NO"
cat "$sysroot"/proc/cmdline | grep jcx-boot-verbose > /dev/null
if [ $? -eq 0 ]; then JCX_VERBOSE="YES"; fi

# If first boot, run setup.
sbegin "Checking if this is the first boot"
if [ ! -e /jcx/checks/firstboot ]
then
	ebegin "First boot! Running setup"
	. /jcx/services/boot/setup-runner
fi

# ----- System Information -----

echo ""
echo -e "\033[1;32mModel\t\t\t\033[1;36m$(cat /proc/device-tree/model)\033[0m" | echoinfo

# get OS release name and version id, running in isolated shell.
(. /etc/os-release; echo -e "\033[1;32mOS Release\t\t\t\033[1;36m$NAME v$VERSION_ID\033[0m" | echoinfo)
echo -e "\033[1;32m$(uname -s)\t\t\t\033[1;36m$(uname -r) ($(uname -m))\033[0m"  | echoinfo
echo -e "\033[1;32mTotal RAM\t\t\t\033[1;36m$(grep "MemTotal" /proc/meminfo | awk '{print $2}')kB (base 10)\033[0m" | echoinfo
echo -e "\033[1;32mIP (eth0)\t\t\t\033[1;36m$(ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | cut -d ' ' -f1)\033[0m" | echoinfo
echo -e "\033[1;32mSHA\t\t\033[1;36m$(cat /jcx/.sha)\033[0m" | echoinfo

echo ""

echo -e "\033[1;35mAPK \033[1;32mInstalled\t\t\033[1;36m$(apk list -I | tee /dev/null | wc -l)\033[0m" | echoinfo
echo -e "\033[1;35mAPK \033[1;32mAvailable (boot)\t\033[1;36m$(apk list -a --repositories-file /media/mmcblk0p1/apks/ | tee /dev/null | wc -l)\033[0m" | echoinfo
echo -e "\033[1;35mAPK \033[1;32mAvailable\t\t\033[1;36m$(apk list -a | tee /dev/null | wc -l)\033[0m" | echoinfo

echo ""

# ----- System Information END -----

# We don't exit 0 here as this is sourced from the openrc task